
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Table MainTable;
	private global::Gtk.HBox hboxNSO;
	private global::Gtk.HBox hboxRename;
	private global::Gtk.HBox hboxStand;
	private global::Gtk.HBox hboxToggle;
	private global::Gtk.Label metadataLabel;
	private global::Gtk.Frame StandFrame;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.Label labelStandFrame;
	private global::Gtk.VBox vboxGrid;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Map Designer");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "stock_fullscreen", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.DefaultWidth = 1024;
		this.DefaultHeight = 576;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.MainTable = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
		this.MainTable.Name = "MainTable";
		this.MainTable.RowSpacing = ((uint)(6));
		this.MainTable.ColumnSpacing = ((uint)(6));
		// Container child MainTable.Gtk.Table+TableChild
		this.hboxNSO = new global::Gtk.HBox ();
		this.hboxNSO.Name = "hboxNSO";
		this.hboxNSO.Homogeneous = true;
		this.hboxNSO.Spacing = 6;
		this.hboxNSO.BorderWidth = ((uint)(1));
		this.MainTable.Add (this.hboxNSO);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.MainTable [this.hboxNSO]));
		w1.TopAttach = ((uint)(1));
		w1.BottomAttach = ((uint)(2));
		w1.XPadding = ((uint)(10));
		w1.YPadding = ((uint)(10));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.hboxRename = new global::Gtk.HBox ();
		this.hboxRename.Name = "hboxRename";
		this.hboxRename.Spacing = 6;
		this.MainTable.Add (this.hboxRename);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.MainTable [this.hboxRename]));
		w2.TopAttach = ((uint)(1));
		w2.BottomAttach = ((uint)(2));
		w2.LeftAttach = ((uint)(2));
		w2.RightAttach = ((uint)(3));
		w2.XPadding = ((uint)(10));
		w2.YPadding = ((uint)(10));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.hboxStand = new global::Gtk.HBox ();
		this.hboxStand.Name = "hboxStand";
		this.hboxStand.Spacing = 6;
		this.MainTable.Add (this.hboxStand);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.MainTable [this.hboxStand]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.LeftAttach = ((uint)(1));
		w3.RightAttach = ((uint)(2));
		w3.XPadding = ((uint)(10));
		w3.YPadding = ((uint)(10));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.hboxToggle = new global::Gtk.HBox ();
		this.hboxToggle.Name = "hboxToggle";
		this.hboxToggle.Spacing = 6;
		this.MainTable.Add (this.hboxToggle);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.MainTable [this.hboxToggle]));
		w4.TopAttach = ((uint)(4));
		w4.BottomAttach = ((uint)(5));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.metadataLabel = new global::Gtk.Label ();
		this.metadataLabel.Name = "metadataLabel";
		this.metadataLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<Selected Stand metadata>");
		this.metadataLabel.Justify = ((global::Gtk.Justification)(1));
		this.MainTable.Add (this.metadataLabel);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.MainTable [this.metadataLabel]));
		w5.TopAttach = ((uint)(4));
		w5.BottomAttach = ((uint)(5));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.StandFrame = new global::Gtk.Frame ();
		this.StandFrame.TooltipMarkup = "Contains all user created Stands for placement";
		this.StandFrame.CanFocus = true;
		this.StandFrame.Name = "StandFrame";
		this.StandFrame.ShadowType = ((global::Gtk.ShadowType)(1));
		this.StandFrame.BorderWidth = ((uint)(1));
		// Container child StandFrame.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		this.StandFrame.Add (this.GtkAlignment);
		this.labelStandFrame = new global::Gtk.Label ();
		this.labelStandFrame.Name = "labelStandFrame";
		this.labelStandFrame.Xalign = 0.6F;
		this.labelStandFrame.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Stands</b>");
		this.labelStandFrame.UseMarkup = true;
		this.StandFrame.LabelWidget = this.labelStandFrame;
		this.MainTable.Add (this.StandFrame);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.MainTable [this.StandFrame]));
		w7.TopAttach = ((uint)(2));
		w7.BottomAttach = ((uint)(4));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XPadding = ((uint)(5));
		w7.YPadding = ((uint)(5));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		// Container child MainTable.Gtk.Table+TableChild
		this.vboxGrid = new global::Gtk.VBox ();
		this.vboxGrid.Name = "vboxGrid";
		this.vboxGrid.Spacing = 6;
		this.MainTable.Add (this.vboxGrid);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.MainTable [this.vboxGrid]));
		w8.TopAttach = ((uint)(2));
		w8.BottomAttach = ((uint)(4));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		this.Add (this.MainTable);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
